# -*- Makefile -*- 

main:
	cd ./library/; make	
	cd ./calibration_fl+fl/; make
	cd ./chat_mit_fl+fl/; make
	

clean: 
	cd ./library/; make clean	
	cd ./calibration_fl+fl/; make clean
	cd ./chat_mit_fl+fl/; make clean
